name: Build

on:
  push:
    branches: [Cube-VK]
  pull_request:
    branches: [Cube-VK]

jobs:
  build_win32_desktop:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x86, x64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: microsoft/setup-msbuild@v1.1
      - run: msbuild ./Demo.sln /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}}
  